### ISSUE TITLE
cut and trim on a pipe or a single step?

### ISSUE THREAD

**Issue by bwlang** [AGROSAVIABIOUNIT/nextflow_conda_cutadapt_trimmo#4]
For large input files it might be helpful  to get only one tool to do all the work with your data.
I think trimmomatic may be able to both apply the quality trimming and adapter detection.

Also, i noticed that you're using file_pair for both processes, but I think the trimmomatic input step is not defining that.
Might be fun to include a fastqc and multiqc step in this pipeline as well (to make it easy to observe the results).

**Comment by AGROSAVIABIOUNIT** [comment]
Sorry, for lateness I didn´t know issue response ability ;) Trimmomatic solve very well adapters at the begin of sequences but internal adapt contamination it is not solve. Poly-AAA contamination is trimmed. You are absolutely right, coming brach will get cutadapt in single process. Last but not less, quality reports and other quality assurance processes will be able when cutadapt has been added to GHRU assembly pipeline (https://gitlab.com/cgps/ghru/pipelines/assembly)

**Comment by AGROSAVIABIOUNIT** [comment]
Single process was set up!
